name: Blueprint
version: ${project.version}
author: Sapphira Tempest
description: Blueprint crafting system designed for HAPPYLAND.

main: io.sn.blueprint.NeoBlueprintCore
depend:
  - Slimefun
  - Dumortierite
  - NBTAPI
  - CommandAPI

api-version: 1.19

libraries:
  - org.clojure:clojure:${clojure.version}
